import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from app.models.lead import Lead

def generate_risk_report(lead: Lead, fmcsa_data: dict) -> bytes:
    """
    Generates a PDF Risk Snapshot in memory.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- HEADER ---
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 50, "CONFIDENTIAL: FLEET DATA RISK SNAPSHOT")
    
    c.setLineWidth(1)
    c.line(50, height - 60, width - 50, height - 60)

    # --- CLIENT PROFILE ---
    y = height - 100
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "CLIENT PROFILE")
    
    c.setFont("Helvetica", 10)
    y -= 20
    c.drawString(50, y, f"Name: {lead.first_name} {lead.last_name}")
    y -= 15
    c.drawString(50, y, f"Company: {lead.company_name}")
    y -= 15
    c.drawString(50, y, f"DOT #: {lead.dot_number}")
    y -= 15
    c.drawString(50, y, f"Fleet Size: {lead.fleet_size}")

    # --- RISK SCORECARD ---
    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "RISK SCORECARD")
    
    y -= 25
    c.setFont("Helvetica-Bold", 14)
    risk_level = fmcsa_data.get('risk_level', 'UNKNOWN')
    
    if risk_level in ["HIGH", "CRITICAL"]:
        c.setFillColor(colors.red)
    elif risk_level == "MODERATE":
        c.setFillColor(colors.orange)
    else:
        c.setFillColor(colors.green)
        
    c.drawString(50, y, f"RISK LEVEL: {risk_level}")
    c.setFillColor(colors.black) # Reset color

    y -= 25
    c.setFont("Helvetica", 10)
    # Handle case where vehicle_oos_rate might be missing or None
    oos_rate = fmcsa_data.get('vehicle_oos_rate', 'N/A')
    c.drawString(50, y, f"Vehicle OOS Rate: {oos_rate}% (National Avg: 22%)")

    # --- FINANCIAL PROJECTIONS (THE HOOK) ---
    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "FINANCIAL IMPACT PROJECTIONS")
    
    y -= 25
    c.setFont("Helvetica-Bold", 10)
    
    if risk_level in ["HIGH", "CRITICAL"]:
        c.setFillColor(colors.red)
        c.drawString(50, y, "⚠ EST. INSURANCE SURCHARGE: $25,000/YR")
        y -= 20
    
    # Simple logic for fuel spend based on fleet size enum if possible, 
    # but for now we'll just show it if risk is present or as a general warning
    c.setFillColor(colors.red)
    c.drawString(50, y, "⚠ EST. UNVERIFIED FUEL SPEND: $8,000/MO")
    c.setFillColor(colors.black)

    # --- FOOTER ---
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, 30, "Generated by Data & AI Clarity Agency | Book your fix at https://fleet-ai-agency.com")

    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer.getvalue()
